name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11" ]
    
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4.5.0"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: scripts/install.sh
      - name: "Run linting tests"
        run: scripts/check.sh
      - name: "Run tests"
        run: scripts/test.sh
